services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - /traffic_processor/influxdb:/var/lib/influxdb
    environment:
     - DOCKER_INFLUXDB_INIT_MODE=setup
     - DOCKER_INFLUXDB_INIT_USERNAME=admin
     - DOCKER_INFLUXDB_INIT_PASSWORD=password 
     - DOCKER_INFLUXDB_INIT_ORG=ark 
     - DOCKER_INFLUXDB_INIT_BUCKET=bucket 
     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret

